Repository ArmaForces/Medical, pull requests merged in 2020-02, with the labels that each got.

#4 Upgrade bandages efficiency
  addons/medical_treatment/ACE_Medical_Treatment.hpp
Labels: feature

#6 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: enhancement, ignore changelog

#7 Move bandage efficiency to macros
  addons/main/script_version.hpp
  addons/medical_treatment/ACE_Medical_Treatment.hpp
  addons/medical_treatment/script_component.hpp
Labels: bugfix, enhancement

#8 Update features overview
  README.md
Labels: documentation, ignore changelog

#10 Bring back standard ACE bandaging time
  README.md
  addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp
Labels: enhancement

#9 Fix Apap treatment icon and litter
  addons/main/data/logo_ca.paa
  addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp
  addons/medical_treatment/CfgVehicles.hpp
  addons/medical_treatment/data/apap_litter.paa
  mod.cpp
Labels: bugfix

#11 Bump version for release 1.0.2
  addons/main/script_version.hpp
Labels: ignore changelog
